<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.irs.gov/efile" xmlns="http://www.irs.gov/efile" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

	<xsd:annotation>
		<xsd:documentation>
			<Description>IRS e-file Schema - Final Year Deductions Explanation</Description>
			<Purpose>Final Year Deductions</Purpose>
			<TaxYear>2026</TaxYear>
			<MaturityLevel>Final Schema Version RL10A Drop 1</MaturityLevel>
			<ReleaseDate>May 28 2026</ReleaseDate>
		</xsd:documentation>
	</xsd:annotation>

	<xsd:include schemaLocation="../../../Common/efileTypes.xsd" />

	<!-- ===================================================================== -->
	<!-- ================= Final Year Deductions Explanation ================= -->
	<!-- ===================================================================== -->

	<xsd:element name="FinalYearDeductionsExplanation">
		<xsd:annotation>
			<xsd:documentation>Final Year Deductions Explanation</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="FinalYearDeductionsExplnType">
					<xsd:attributeGroup ref="DocumentAttributes">
						<xsd:annotation>
							<xsd:documentation>Common return document attributes</xsd:documentation>
						</xsd:annotation>
					</xsd:attributeGroup>
					<xsd:attribute name="documentName" type="StringType" fixed="FinalYearDeductionsExplanation">
						<xsd:annotation>
							<xsd:documentation>IRS internal use only. To avoid error in the return, do not include the attribute name or value.</xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="FinalYearDeductionsExplnType">
		<xsd:annotation>
			<xsd:documentation>Content model for Final Year Deductions Explanation</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="ShortExplanationTxt" type="ShortExplanationType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>
